language: erlang
sudo: false

env:
  global:
    - BASELINE=ProjectXX
  matrix:
    - SMALLTALK="SqueakTrunk"
    # - SMALLTALK="Squeak4.5"

addons:
  apt:
    packages:
    # 32-bit VM
    - libc6:i386
    # UUIDPlugin
    - libuuid1:i386

install:
   - export PROJECT_HOME="$(pwd)"
   - cd $HOME
   - wget -q -O filetreeCI.zip https://github.com/fniephaus/filetreeCI/archive/master.zip
   - unzip -q filetreeCI.zip
   - cd filetreeCI-*
   - export FILETREE_CI_HOME="$(pwd)"

script: $FILETREE_CI_HOME/run.sh

before_install:
- openssl aes-256-cbc -K $encrypted_c05dcaa1178f_key -iv $encrypted_c05dcaa1178f_iv
  -in setLoginKey.st.enc -out packages/ProjectXX-Tests.package/GitHubIssueIntegrationTest.class/instance/setLoginKey.st
  -d
